% Creates a patch object for displaying cell boundaries
function create_custom_patch(axes, boundariesX, boundariesY, patchColor)
    patch(axes, boundariesX, boundariesY, 'k', ...
          'EdgeAlpha', 1, ...
          'LineWidth', 0.1, ...
          'EdgeColor', patchColor, ...
          'Tag', 'Patch' ...
    );
end