function plot_bar_rectangle(ax, data, yLim, colors)
    % Data is an array of size 1 x 3, containing the cell stats
    x_start = 0;
    for i = 1:length(data)
        x_width = data(i);
        text_starting_point = x_start+x_width/2;

        rectangle('Parent', ax, ...
            'Position',[x_start, yLim, x_width, 1], ...
            'FaceColor', colors(i, :) ...
            );

        if (x_width ~= 0)
            text('Parent', ax, ...
                'Position', [text_starting_point, yLim + 0.5, 0], ...
                'String', num2str(x_width), ...
                'HorizontalAlignment', 'center', ...
                'Color','k' ...
                );
        end
        x_start = x_start + x_width; 
    end
end